version: '3.9'

services:
  node:
    container_name: express-docker-node-prod
    ports:
      - '9092:4000'
    image: mayallo/docker-express
    build:
      context: .
      target: production
    command: npm run start
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://root:example@mongo:27017/
    # env_file:
    #   - .env
    networks:
      - docker-express-prod
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - 'mongo-data-prod:/data/db'
    networks:
      - docker-express-prod

  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - docker-express-prod

volumes:
  mongo-data-prod:

networks:
  docker-express-prod:
