version: '3.9'

services:
  node:
    container_name: express-docker-node-dev
    ports:
      - '9091:4000'
    build:
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - './src:/app/src:ro'
    environment:
      - NODE_ENV=development
