name: Goodbye

run-name: goodbye-run-name

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: |
          echo "hello!"
        shell: bash

  say_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: bye
        run: echo "goodbye"

