name: Goodbye

run-name: goodbye-run-name

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:  
      - name: hello
      - uses: actions/checkout@v2
      - run: |
          echo "hello!"

  say_goodbye:
    runs-on: ubuntu-latest
    steps:
      - run: echo "goodbye"
      
      

